name: flare_loading
description: Loading widget based on a custom Flare animation, allow you to create beautiful custom loading widgets or dialogs
version: 3.0.0
homepage: https://github.com/jaumard/flare_loading

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.0.2"

dependencies:
  flare_flutter:
    git:
      url: https://github.com/AmrNRD/Flare-Flutter
      path: flare_flutter/
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
